# Generated by Django 5.1.5 on 2025-02-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='contacted_properties',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='inquiries',
            field=models.ManyToManyField(blank=True, to='realestateapp.inquiry'),
        ),
    ]
